export default {
  author_association: "NONE",
  closed_at: null,
  comments: 0,
  comments_url: "",
  created_at: new Date().toISOString(),
  events_url: "",
  html_url: "https://github.com/ubiquity/test-repo/pull/3",
  id: 3,
  labels_url: "",
  locked: false,
  milestone: null,
  node_id: "3",
  owner: "ubiquity",
  number: 3,
  repository_url: "https://github.com/ubiquity/test-repo",
  state: "open",
  title: "PR: issue",
  updated_at: "",
  url: "https://api.github.com/repos/ubiquity/test-repo/pulls/3",
  user: {
    id: 1,
    login: "ubiquity",
  },
  repo: "test-repo",
  body: "Resolves #1",
  // Additional PR-specific fields
  additions: 0,
  base: {
    ref: "main",
    sha: "",
    repo: {
      name: "test-repo",
      owner: {
        id: 1,
        login: "ubiquity",
      },
      full_name: "ubiquity/test-repo",
    },
  },
  changed_files: 0,
  commits: 0,
  deletions: 0,
  diff_url: "https://github.com/ubiquity/test-repo/pull/3.diff",
  draft: false,
  head: {
    ref: "feature-branch",
    sha: "",
    repo: {
      full_name: "ubiquity/test-repo",
    },
  },
  merge_commit_sha: null,
  mergeable: null,
  merged: false,
  merged_at: null,
  merged_by: null,
  patch_url: "https://github.com/ubiquity/test-repo/pull/3.patch",
  rebaseable: null,
  review_comments: 0,
  review_comments_url: "",
};
